{% set name = "grafana-client" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grafana-client-{{ version }}.tar.gz
  sha256: 3de4a11d9d893b511f4d6d2efd9b92de1350c7f59486d7a48e8a68615d206bcd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools-scm <8
    - pip
  run:
    - python >=3.6
    - requests >=2.23.0,<3
    - dataclasses
    - importlib-metadata

test:
  imports:
    - grafana_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/panodata/grafana-client
  summary: A client library for accessing the Grafana HTTP API, written in Python
  dev_url: https://github.com/panodata/grafana-client
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marie59
